# Add labels when PR opened.
name: PR_Labeler

on:
  workflow_call:
    inputs:
      PR_NUMBER:
        type: string
      BRANCH_NAME:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    env:
      GH_TOKEN: "${{ github.token }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Label PRs
        run: |
          l1=$(echo "${{ github.event.inputs.PR_NUMBER }}" | sed "s/\/.*//")
          l2=$(echo "${{ github.event.inputs.PR_NUMBER }}" | sed "s/.*\///")
          echo $l1
          echo $l2
          gh pr edit "${{ github.event.inputs.BRANCH_NAME }}" --add-label $l1
          gh pr edit "${{ github.event.inputs.BRANCH_NAME }}" --add-label $l2

