# Add labels when PR opened.
name: PR_Labeler

on:
  workflow_call:
    inputs:
      pr_number:
        type: string
        description: 'Pull Request Number'
        default: ''
      branch_name:
        type: string
        description: 'Base Branch Name'
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    env:
      GH_TOKEN: "${{ github.token }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Label PRs
        run: |
          echo "${{ inputs.branch_name }}"
          l1=$(echo "${{ inputs.branch_name }}" | sed "s/\/.*//")
          l2=$(echo "${{ inputs.branch_name }}" | sed "s/.*\///")
          echo $l1
          echo $l2
          gh pr edit "${{ inputs.pr_number }}" --add-label $l1
          gh pr edit "${{ inputs.pr_number }}" --add-label $l2

